const LOGIN_START = "LOGIN_START"
const LOGIN_SUCCESS = "LOGIN_SUCCESS"
const LOGIN_FAILURE = "LOGIN_FAILURE"
const SIGNUP_START = "SIGNUP_START"
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
const SIGNUP_FAILURE = "SIGNUP_FAILURE"


export { LOGIN_FAILURE, LOGIN_START, LOGIN_SUCCESS, SIGNUP_FAILURE, SIGNUP_SUCCESS, SIGNUP_START }